### ISSUE TITLE
Comparing free energies of training/validaton sets while training

### ISSUE THREAD

**Issue by starkdg** [Cospel/rbm-tf#4]
Hi. Great work on this project.  I was just wondering if you've done any work on calculation of free energies of the model.  The Hinton paper warns against using the reconstruction cost function as a guide and suggests using the ratio of average free energies from training and validation sets.   Any direction in this area?

**Comment by Cospel** [comment]
Hi, I don't work with RBM for more than 2 years, so I don't have any advice for it. But if you have time it will be great to implement it.
